# Default values for minecraft-team1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: openhack/minecraft-server
  tag: "2.0"

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
