apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft-team1.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "minecraft-team1.name" . }}
    helm.sh/chart: {{ include "minecraft-team1.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: game
    - port: 25575
      targetPort: 25575
      protocol: TCP
      name: rcon
  selector:
    app.kubernetes.io/name: {{ include "minecraft-team1.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
